[graph]
all-features = true

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "CC0-1.0",
    "AGPL-3.0"
]
copyleft = "allow"

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"

[sources]
unknown-source = "warn"
