#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0
# Copyright (C) 2024-2026 Breakdown RS Contributors
# Co-authored-by: omen-alpha (opencode-go)

set -euo pipefail

# One-command AI-import enablement for the host-run dev API (issue #428).
#
# A `cargo run --bin api` started on the host cannot reach the internal-only
# dev Garage, and `AI_IMPORT_ENABLED=1` fails closed (#181 — no in-memory
# payload fallback) until durable payload storage is configured. This script
# performs the whole sequence:
#
#   1. Boots the dev compose with the AI overlay (docker-compose.dev.ai.yml),
#      which publishes Garage's S3 (:3900) and admin (:3902) ports to the host.
#   2. Provisions Garage: cluster layout, the costume-photos bucket (ADR-019)
#      and the ai-import-payloads bucket, plus a fixed dev-only S3 key.
#   3. Verifies both ports are reachable from the host.
#   4. Writes `.env.dev-ai.local` (git-ignored, chmod 600) with the complete
#      AI-import environment for the host-run API.
#
# Usage (from `backend/`):
#   ./scripts/enable-dev-ai-import.sh            # boot + provision + env file
#   ./scripts/enable-dev-ai-import.sh --run      # also start the API afterwards
#
# The script is idempotent: Garage roles are only assigned when missing,
# bucket/key creation errors on "already exists" are tolerated, and the env
# file is rewritten with the same deterministic values.
#
# Dev-only credentials: the S3 access key and secret are derived
# deterministically from fixed dev-only strings (gitleaks-clean derivation —
# no high-entropy literal is committed). Never reuse these outside a local
# dev Garage; production provisiones real keys via the ops runbook.

cd "$(dirname "$0")/.."

COMPOSE_ARGS=(-f docker-compose.dev.yml -f docker-compose.dev.ai.yml)
ADMIN_TOKEN="${GARAGE_ADMIN_TOKEN:-garage_admin_dev}"
ENV_FILE=".env.dev-ai.local"

# Deterministic dev-only S3 credentials (see header note).
ACCESS_KEY="GK$(printf 'breakdown-dev-only-s3-key-id' | sha256sum | cut -c1-24)"
SECRET_KEY="$(printf 'breakdown-dev-only-s3-secret' | sha256sum | cut -d' ' -f1)"

echo "==> Booting dev runtime with AI overlay (Garage ports published to host)"
docker compose "${COMPOSE_ARGS[@]}" up -d
# Re-render the Garage config one-shot and restart Garage against it, so the
# rendered TOML always matches the current dev defaults.
docker compose "${COMPOSE_ARGS[@]}" up -d --force-recreate garage-config garage

echo "==> Waiting for Garage to become healthy"
for _ in $(seq 1 30); do
    if [ "$(docker inspect --format='{{.State.Health.Status}}' "$(docker compose "${COMPOSE_ARGS[@]}" ps -q garage)")" = "healthy" ]; then
        break
    fi
    sleep 2
done

# Run the Garage CLI inside the (bare-binary) garage container against its own
# config + admin token. Each call is a direct exec — the image has no shell.
gcli() {
    docker compose "${COMPOSE_ARGS[@]}" exec -T garage \
        /garage -c /etc/garage/config.toml --admin-token "$ADMIN_TOKEN" "$@"
}

echo "==> Ensuring Garage cluster layout (single-node, dev)"
if gcli status 2>/dev/null | grep -q "NO ROLE ASSIGNED"; then
    NODE_ID="$(gcli status 2>/dev/null | awk '/==== HEALTHY NODES ====/{getline; print $1}')"
    gcli layout assign -z dc1 -c 1G "$NODE_ID"
    VERSION="$(gcli layout show 2>/dev/null | sed -n 's/^Current cluster layout version: //p')"
    gcli layout apply --version "$VERSION"
else
    echo "    Cluster layout already assigned — skipping"
fi

echo "==> Provisioning buckets + S3 key (dev)"
# Idempotency: existing buckets/keys error out on re-create; that is the
# expected path on re-runs, matching scripts/provision-garage.sh behavior.
gcli bucket create costume-photos 2>/dev/null || true
gcli bucket create ai-import-payloads 2>/dev/null || true
gcli key import "$ACCESS_KEY" "$SECRET_KEY" -n breakdown-api --yes 2>/dev/null || true
for bucket in costume-photos ai-import-payloads; do
    gcli bucket allow --read --write --owner "$bucket" --key "$ACCESS_KEY" >/dev/null
done

echo "==> Verifying host reachability"
if ! curl -sf http://localhost:3902/v1/status \
        -H "Authorization: Bearer $ADMIN_TOKEN" >/dev/null; then
    echo "Garage admin API not reachable on localhost:3902" >&2
    exit 1
fi
# Any HTTP answer (403 unauthenticated included) proves the S3 port is open.
if ! curl -s -o /dev/null http://localhost:3900/; then
    echo "Garage S3 API not reachable on localhost:3900" >&2
    exit 1
fi
echo "    S3 (localhost:3900) and admin API (localhost:3902) reachable"

echo "==> Writing $ENV_FILE"
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/enable-dev-ai-import.sh (issue #428). Git-ignored.
# AI import with durable Garage payload storage for the host-run dev API.
AI_IMPORT_ENABLED=1
AI_PAYLOAD_S3_ENDPOINT=http://localhost:3900
AI_PAYLOAD_S3_ACCESS_KEY=$ACCESS_KEY
AI_PAYLOAD_S3_SECRET_KEY=$SECRET_KEY
AI_PAYLOAD_S3_BUCKET=ai-import-payloads
DATABASE_URL=postgres://postgres:postgres@localhost:5432/breakdown
SIERRADB_URL=redis://127.0.0.1:9090/?protocol=resp3
EOF
chmod 600 "$ENV_FILE"

echo ""
echo "AI import is enabled for the host-run dev API."
echo ""
echo "Start the API with:"
echo "  set -a; . ./$ENV_FILE; set +a; cargo run -p api"
echo "(or re-run this script with --run to do that now)"

if [ "${1:-}" = "--run" ]; then
    echo ""
    echo "==> Starting the API (AI import enabled)"
    set -a
    # shellcheck disable=SC1090
    . "$ENV_FILE"
    set +a
    exec cargo run -p api
fi
