#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0
# Copyright (C) 2024-2026 Breakdown RS Contributors
# Co-authored-by: deepseek-v4-flash (neuralwatt)

set -euo pipefail

# One-command Vault enablement for the host-run dev API (issue #468).
#
# The base dev compose runs no Vault (ADR-027 is prod-only), so a host-run
# `cargo run --bin api` cannot reach the transit + KV-v2 engines the
# `/settings` credential and AI-config `vault_key_id` flows need — those
# endpoints 503. This script performs the whole sequence:
#
#   1. Boots the Vault overlay (docker-compose.dev.vault.yml), which publishes
#      Vault's HTTP API on loopback `127.0.0.1:8200` — dev-only plaintext
#      (tls_disable in vault/config.dev.hcl); never acceptable in production
#      (ADR-024/ADR-027).
#   2. Runs the prod `vault-bootstrap` one-shot (same script/image as prod,
#      parameterized so TLS is opt-in): init + unseal, Transit + KV-v2, the
#      `breakdown-app` policy, and a least-privilege 24 h app token.
#   3. Persists the unseal key + app token into the git-ignored `.vault-dev/`
#      host directory and writes `.env.dev-vault.local` (git-ignored, chmod
#      600) with `VAULT_ADDR` + `VAULT_APP_TOKEN_FILE` for the host-run API.
#
# Usage (from `backend/`):
#   ./scripts/enable-dev-vault.sh             # full boot + provision + env
#   ./scripts/enable-dev-vault.sh --finalize  # post-provision only (no docker
#                                             # calls) — used by
#                                             # enable-dev-ai-import.sh, which
#                                             # boots/provisions with its own
#                                             # combined compose invocation set
#
# The script is idempotent: on re-runs the one-shot renews the existing app
# token (24 h period) instead of re-provisioning. Reset everything:
#   docker compose -f docker-compose.dev.vault.yml down -v && rm -rf .vault-dev

cd "$(dirname "$0")/.."

COMPOSE=(docker compose -f docker-compose.dev.vault.yml)
VAULT_DIR=".vault-dev"
APP_TOKEN="$VAULT_DIR/app-token/app.token"
BOOTSTRAP_TOKEN_FILE="$VAULT_DIR/bootstrap.token"
ENV_FILE=".env.dev-vault.local"

FINALIZE=0
if [ "${1:-}" = "--finalize" ]; then
    FINALIZE=1
fi

mkdir -p "$VAULT_DIR" "$VAULT_DIR/unseal" "$VAULT_DIR/app-token"
umask 077
if [ ! -s "$BOOTSTRAP_TOKEN_FILE" ]; then
    # Dev-only bootstrap seed for the shared vault-bootstrap.sh (required to be
    # non-empty; a recovery seed on repair). Random so it is never mistaken for
    # a real secret; git-ignored via .vault-dev/.
    head -c 32 /dev/urandom | base64 > "$BOOTSTRAP_TOKEN_FILE"
fi
chmod 600 "$BOOTSTRAP_TOKEN_FILE"
umask 022

if [ "$FINALIZE" = "1" ]; then
    echo "==> Vault finalize mode (boot/provision done by the caller)"
else
    echo "==> Booting Vault overlay (HTTP API on 127.0.0.1:8200, dev-only plaintext)"
    "${COMPOSE[@]}" up -d vault

    echo "==> Running vault-bootstrap (init/unseal/engines/policy/app-token)"
    "${COMPOSE[@]}" run --rm vault-bootstrap
fi

# Re-align ownership of the whole git-ignored state dir to the invoking host
# user: the app token must be readable by the host-run API, and a later
# `rm -rf .vault-dev` reset must work without root. The bootstrap one-shot
# (root in the container) is unaffected — root can read/write these files
# regardless of ownership. Modes stay as written (app token 600, unseal key
# 600).
if [ -d "$VAULT_DIR" ]; then
    chown -R "$(id -u):$(id -g)" "$VAULT_DIR" 2>/dev/null || true
fi

echo "==> Verifying host reachability"
if ! curl -fsS "http://127.0.0.1:8200/v1/sys/health?standbyok=true" 2>/dev/null | grep -q '"sealed":false'; then
    echo "ERROR: Vault not initialized/unsealed and reachable on localhost:8200" >&2
    [ -r "$APP_TOKEN" ] || echo "ERROR: app token not readable at $APP_TOKEN" >&2
    exit 1
fi
[ -r "$APP_TOKEN" ] || {
    echo "ERROR: Vault app token is not readable at $APP_TOKEN — run as the host user" >&2
    exit 1
}
echo "    Vault reachable and unsealed on localhost:8200; app token ready"

echo "==> Writing $ENV_FILE"
# Absolute path so the token resolves regardless of the API's cwd when the
# file is sourced/exported.
APP_TOKEN_ABS="$(pwd)/$APP_TOKEN"
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/enable-dev-vault.sh (issue #468). Git-ignored.
# Dev Vault (docker-compose.dev.vault.yml) for the host-run dev API.
VAULT_ADDR=http://127.0.0.1:8200
VAULT_APP_TOKEN_FILE=$APP_TOKEN_ABS
EOF
chmod 600 "$ENV_FILE"

# Re-export the VAULT_* vars for the current shell so a follow-up `--run`
# invocation in the same terminal picks them up without re-sourcing.
export VAULT_ADDR=http://127.0.0.1:8200
export VAULT_APP_TOKEN_FILE="$APP_TOKEN_ABS"

echo ""
echo "Vault is enabled for the host-run dev API."
echo ""
echo "Load the generated env (or let enable-dev-ai-import.sh merge it):"
echo "  set -a; . ./$ENV_FILE; set +a; cargo run -p api"
echo ""
echo "Reset with:  docker compose -f docker-compose.dev.vault.yml down -v && rm -rf .vault-dev"
