// SPDX-License-Identifier: AGPL-3.0
// Copyright (C) 2024-2026 Breakdown RS Contributors
// Co-authored-by: hy3 (opencode-go)

// Regression guard for issue #313: the dev flavor's pinned CA asset
// (`assets/certs/dev/ca.pem`) must be the REAL dev CA generated by
// `backend/scripts/generate-dev-certs.sh` — the trust anchor that actually
// signs the dev IdP (`:3301`) and API (`:3000`) leaf certs — and must NOT be
// the prod placeholder. The prod placeholder is tracked separately and must
// remain a distinct, independently-parseable CA.
//
// These assertions encode the issue's acceptance criteria at the unit level:
// the bundled PEM is a valid, parseable pinned CA (the client can load and
// trust it), and dev is not the prod placeholder. The actual chain trust
// (dev CA → IdP leaf cert for localhost / 10.0.2.2) is proven separately with
// `openssl verify` against the backend-generated leaf certs.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:frontend_flutter/app_config.dart';
import 'package:frontend_flutter/src/network/api_client.dart';

const _devCaPath = 'assets/certs/dev/ca.pem';
const _prodCaPath = 'assets/certs/prod/ca.pem';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  const config = AppConfig(
    flavor: Flavor.dev,
    apiBase: 'https://api.breakdown.rs',
    oidcIss: 'https://idp.example',
    devAuthSub: '',
    oidcAudience: 'aud',
    oidcClientId: 'c',
    oidcRedirectUri: 'breakdown://redirect',
    devIdpInsecure: '',
  );

  // Mirror of `config` for the prod flavor, used to exercise the prod
  // asset-loading branch. `loadPinnedSecurityContext` itself does not enforce
  // the prod-only https assert (that lives in `buildApiClient`), so an https
  // base URL is sufficient here.
  const prodConfig = AppConfig(
    flavor: Flavor.prod,
    apiBase: 'https://api.breakdown.rs',
    oidcIss: 'https://idp.example',
    devAuthSub: '',
    oidcAudience: 'aud',
    oidcClientId: 'c',
    oidcRedirectUri: 'breakdown://redirect',
    devIdpInsecure: '',
  );

  group('pinned CA assets (issue #313 — dev CA alignment)', () {
    test('dev asset is a real, parseable pinned CA', () async {
      final pem = await File(_devCaPath).readAsString();
      // Throws TlsConfigError (fail-closed) on a non-PEM / unparseable body,
      // so reaching here proves the asset is a valid pinned CA.
      final ctx = await loadPinnedSecurityContext(config, inlinePem: pem);
      expect(ctx, isA<SecurityContext>());
    });

    test('prod asset remains a distinct, parseable pinned CA', () async {
      final pem = await File(_prodCaPath).readAsString();
      final ctx = await loadPinnedSecurityContext(config, inlinePem: pem);
      expect(ctx, isA<SecurityContext>());
    });

    test('dev CA is NOT the prod placeholder (tracked separately)', () async {
      final dev = await File(_devCaPath).readAsBytes();
      final prod = await File(_prodCaPath).readAsBytes();
      expect(dev, isNot(equals(prod)));
    });

    // The three tests above inject the PEM via the `inlinePem` seam and never
    // touch `rootBundle`. The next two exercise the REAL production path
    // (`rootBundle.loadString('assets/certs/<flavor>/ca.pem')`), proving the
    // assets are actually bundled/registered for both flavors — a broken
    // flavor selection or a missing asset registration would fail these even
    // though the inlinePem tests pass.
    test(
      'dev asset loads from the bundled rootBundle (no inlinePem)',
      () async {
        final ctx = await loadPinnedSecurityContext(config);
        expect(ctx, isA<SecurityContext>());
      },
    );

    test(
      'prod asset loads from the bundled rootBundle (no inlinePem)',
      () async {
        final ctx = await loadPinnedSecurityContext(prodConfig);
        expect(ctx, isA<SecurityContext>());
      },
    );
  });
}
