# SPDX-License-Identifier: AGPL-3.0
# Copyright (C) 2024-2026 Breakdown RS Contributors
# Co-authored-by: hy3 (opencode-go)

name: breakdown_lints
description: Breakdown RS custom analyzer plugin (analysis_server_plugin).
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.1

dependencies:
  analysis_server_plugin: 0.3.18
  analyzer: ^13.3.0
