// SPDX-License-Identifier: AGPL-3.0
// Copyright (C) 2024-2026 Breakdown RS Contributors
// Co-authored-by: glm-5.3 (neuralwatt)
// Co-authored-by: glm-5.3-flash (opencode-go)

//! Reservation store (ADR-036): atomic cross-aggregate uniqueness claims on
//! synthetic SierraDB streams.
//!
//! `reserve` appends a `ReservationReserved` event to the key's stream with
//! `ExpectedVersion::Empty`; a competing reserve fails the version condition
//! *in the event store* (`ErrorCode::WrongVer`) and maps to the invariant's
//! registered 409 before any aggregate append. The claim is released with a
//! CAS-guarded `ReservationReleased` append (only the holder releases, only
//! while its claim is still the top of the stream). After a release the key is
//! re-claimable via `ExpectedVersion::Exact(last_stream_version)`; a claim
//! whose payload matches the same `aggregate_id` is owned by the retry itself
//! (idempotent AI-apply recovery, mirroring issue #182).
//!
//! This is infrastructure write-side code operating on the event store — it
//! touches no read-model projection (CQRS boundary). The projector table built
//! from the reservation events (`projection_number_reservation`) is
//! observability and reaper candidate selection only.
//!
//! Raw `EAPPEND` is used instead of the `kameo_es` `CommandService` actor
//! machinery: reservations are not aggregates, and the CAS/re-read loop must
//! sit on one linearizable per-stream order, which `EAPPEND` expected
//! versions provide.
//!
//! Event payloads are CBOR (mirroring the `kameo_es` envelope convention);
//! event ids, timestamps and partition coordinates are generated by SierraDB
//! exactly as for domain events.

use breakdown_core::error::DomainError;
use kameo_es::ConnectionPool;
use redis::aio::MultiplexedConnection;
use serde::de::DeserializeOwned;
use sierradb_client::{
    AppendInfo, AsyncTypedCommands, ErrorCode, Event, ExpectedVersion, SierraError,
    stream_partition_key,
};
use uuid::Uuid;

use super::event::{
    EVENT_NAME_CONSUMED, EVENT_NAME_RELEASED, EVENT_NAME_RESERVED, RESERVATION_STREAM_PREFIX,
    ReservationEvent, ReservationKind, reservation_stream_id,
};

/// Bounded retry budget for the reserve CAS loop. Each lost CAS means a
/// concurrent claimer won the rare released-stream race between our read and
/// our append; re-reading and retrying converges because SierraDB per-stream
/// appends are linearizable. Beyond the budget the conflict is surfaced
/// instead of retry-looping forever.
const RESERVE_RETRY_BUDGET: usize = 3;

/// A successfully held claim. `claim_version` is the SierraDB stream version
/// of this claim's own `ReservationReserved` event and is the CAS token that
/// must accompany any release of it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReservationClaim {
    pub key: String,
    pub aggregate_id: Uuid,
    pub claim_version: u64,
}

/// The authoritative last lifecycle state of a reservation stream (event
/// store read, not a projector row — the reaper acts only against these
/// versions so projection lag can be at most wasteful, never wrong).
#[derive(Debug, Clone)]
pub struct StreamState {
    pub variant: LifecycleVariant,
    pub aggregate_id: Uuid,
    pub stream_version: u64,
    /// SierraDB timestamp of the last lifecycle event — the reaper's TTL
    /// clock on the AUTHORITATIVE claim.
    pub timestamp: std::time::SystemTime,
}

/// Which lifecycle event tops the stream.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LifecycleVariant {
    Reserved,
    Released,
    Consumed,
}

/// Raw reservation-stream claim store (ADR-036 §2). Cheap to clone: it holds
/// only a pooled connection handle.
#[derive(Clone)]
pub struct ReservationStore {
    pool: ConnectionPool,
}

impl std::fmt::Debug for ReservationStore {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ReservationStore").finish_non_exhaustive()
    }
}

impl ReservationStore {
    pub fn new(pool: kameo_es::ConnectionPool) -> Self {
        Self { pool }
    }

    /// Claims the key for `aggregate_id` atomically.
    ///
    /// `conflict` is the invariant's registered problem-code [`DomainError`]
    /// (ADR-031) returned on a lost race, so the API-edge pre-check 409 and
    /// this atomic-race 409 share one stable code per invariant.
    pub async fn reserve(
        &self,
        key: &str,
        aggregate_id: Uuid,
        conflict: DomainError,
    ) -> Result<ReservationClaim, DomainError> {
        let stream_id = reservation_stream_id(key);

        // `Some(v)` = CAS at stream version `v` (re-reserve after a release);
        // `None` = fresh-stream claim (`ExpectedVersion::Empty`).
        let mut cas_at: Option<u64> = None;

        for attempt in 0..=RESERVE_RETRY_BUDGET {
            let mut connection = self.pool.get();
            let expected = cas_at.map_or(ExpectedVersion::Empty, ExpectedVersion::Exact);

            match self
                .append_lifecycle(
                    &mut connection,
                    &stream_id,
                    EVENT_NAME_RESERVED,
                    expected,
                    &ReservationEvent::Reserved { aggregate_id },
                )
                .await?
            {
                Some(info) => {
                    return Ok(ReservationClaim {
                        key: key.to_owned(),
                        aggregate_id,
                        claim_version: info.stream_version,
                    });
                }
                None => {
                    // The stream exists — classify it from the event store.
                    match self
                        .claim_obstacle(&mut connection, &stream_id, aggregate_id)
                        .await?
                    {
                        ClaimObstacle::OwnedBySelf(existing) => {
                            // A previous attempt of the same aggregate already
                            // holds this key (crash between reserve and
                            // aggregate append; the AI-apply retry re-derives
                            // the same id, issue #182 mirror). Hold it as ours.
                            tracing::info!(
                                key,
                                aggregate = %aggregate_id,
                                version = existing.claim_version,
                                "reservation claim recovered from this aggregate's own stream (ADR-036 §2)",
                            );
                            return Ok(existing);
                        }
                        ClaimObstacle::Claimable(at) => {
                            cas_at = Some(at);
                        }
                        ClaimObstacle::ClaimableAtFreshStream => {
                            cas_at = None;
                        }
                        ClaimObstacle::Permanent => {
                            tracing::info!(
                                key,
                                aggregate = %aggregate_id,
                                attempt,
                                "reservation claim lost to a permanent holder (ADR-036 §2)",
                            );
                            return Err(conflict);
                        }
                    }
                }
            }
        }

        // Reached only when every classification said "claimable" but every
        // CAS lost the linearizable race.
        tracing::info!(
            key,
            attempts = RESERVE_RETRY_BUDGET + 1,
            "reservation claim raced too often; surfacing conflict (ADR-036 §2)",
        );
        Err(conflict)
    }

    /// Releases the claim (create-failure compensation, ADR-036 §3.1): the
    /// CAS guard ensures only the holder releases and only while its own
    /// claim is still the top of the stream. Returns `true` when the release
    /// event was appended, `false` on a CAS miss.
    ///
    /// A CAS miss is never an error: whatever was appended above the holder's
    /// `ReservationReserved` event (the reaper releasing the same orphan, or
    /// a consumed marker) settles the key either way — that observation is
    /// logged and the claim counts as resolved.
    pub async fn release(
        &self,
        key: &str,
        aggregate_id: Uuid,
        at_version: u64,
    ) -> Result<bool, DomainError> {
        let stream_id = reservation_stream_id(key);
        let mut connection = self.pool.get();

        let appended = self
            .append_lifecycle(
                &mut connection,
                &stream_id,
                EVENT_NAME_RELEASED,
                ExpectedVersion::Exact(at_version),
                &ReservationEvent::Released { aggregate_id },
            )
            .await?;

        if appended.is_none() {
            tracing::debug!(
                key,
                aggregate = %aggregate_id,
                "reservation release lost its CAS race; key already resolved (ADR-036 §3.1)",
            );
        }
        Ok(appended.is_some())
    }

    // ---- reaper-facing helpers (ADR-036 §3.2) --------------------------------

    /// Parses the last lifecycle event of a reservation stream.
    ///
    /// `None` = stream absent or its top event is unknown to this version.
    /// This is the reaper's authoritative read; a lagging claim projection
    /// can never feed a wrong decision because the reaper runs its writes
    /// against THESE versions only.
    pub async fn last_state(&self, key: &str) -> Result<Option<StreamState>, DomainError> {
        let stream_id = reservation_stream_id(key);
        let mut connection = self.pool.get();

        let Some(last) = self.last_stream_event(&mut connection, &stream_id).await? else {
            return Ok(None);
        };

        let variant = match last.event_name.as_str() {
            EVENT_NAME_RESERVED => LifecycleVariant::Reserved,
            EVENT_NAME_RELEASED => LifecycleVariant::Released,
            EVENT_NAME_CONSUMED => LifecycleVariant::Consumed,
            other => {
                tracing::warn!(
                    key,
                    event = other,
                    "unknown event on reservation stream; reaper will not act (ADR-036 §3.2)",
                );
                return Ok(None);
            }
        };
        let aggregate_id =
            decode_lifecycle::<ReservationEvent>(&last.payload, &stream_id)?.aggregate_id();

        Ok(Some(StreamState {
            variant,
            aggregate_id,
            stream_version: last.stream_version,
            timestamp: last.timestamp,
        }))
    }

    /// Reaper action for a realized claim: appends `ReservationConsumed`
    /// (CAS-guarded on the observed stream version). Returns `true` when
    /// appended, `false` on a CAS miss (claim changed meanwhile — resolved).
    pub async fn consume(
        &self,
        key: &str,
        aggregate_id: Uuid,
        at_version: u64,
    ) -> Result<bool, DomainError> {
        let stream_id = reservation_stream_id(key);
        let mut connection = self.pool.get();

        let appended = self
            .append_lifecycle(
                &mut connection,
                &stream_id,
                EVENT_NAME_CONSUMED,
                ExpectedVersion::Exact(at_version),
                &ReservationEvent::Consumed { aggregate_id },
            )
            .await?;
        Ok(appended.is_some())
    }

    /// Reaper's aggregate-existence probe: does the claimed aggregate's event
    /// stream hold at least one event (`esver` on the event store — never a
    /// projection, so projector lag cannot cause a false release; ADR-036
    /// §3.2)?
    pub async fn aggregate_stream_exists(
        &self,
        kind: ReservationKind,
        aggregate_id: Uuid,
    ) -> Result<bool, DomainError> {
        let aggregate_stream = format!("{}-{}", kind.aggregate_category(), aggregate_id);
        let mut connection = self.pool.get();
        Ok(connection
            .esver(&aggregate_stream)
            .await
            .map_err(SierraError::from)
            .map_err(sierra_error)?
            .is_some())
    }

    /// Classifies the stream state for a failed claim attempt, from the event
    /// store itself (never a projection — ADR-036 §3.2).
    async fn claim_obstacle(
        &self,
        connection: &mut MultiplexedConnection,
        stream_id: &str,
        aggregate_id: Uuid,
    ) -> Result<ClaimObstacle, DomainError> {
        let Some(last) = self.last_stream_event(connection, stream_id).await? else {
            // The version conflict promised a non-empty stream; an empty
            // read means an unexpected server state. A fresh attempt is
            // the only safe reaction.
            tracing::warn!(
                stream_id,
                "version conflict against an empty reservation-stream read; retrying (ADR-036 §2)",
            );
            return Ok(ClaimObstacle::ClaimableAtFreshStream);
        };

        match last.event_name.as_str() {
            EVENT_NAME_RESERVED => match decode_lifecycle(&last.payload, stream_id)? {
                ReservationEvent::Reserved {
                    aggregate_id: holder,
                } if holder == aggregate_id => Ok(ClaimObstacle::OwnedBySelf(ReservationClaim {
                    key: stream_key(stream_id),
                    aggregate_id,
                    claim_version: last.stream_version,
                })),
                _ => Ok(ClaimObstacle::Permanent),
            },
            EVENT_NAME_RELEASED => Ok(ClaimObstacle::Claimable(last.stream_version)),
            EVENT_NAME_CONSUMED => match decode_lifecycle(&last.payload, stream_id)? {
                // The reaper marked the claim realized — the key is owned by
                // the consuming aggregate forever. A RETRY of the SAME
                // aggregate (AI-apply crash recovery, issue #182 mirror: the
                // reaper can consume the claim between a crashed attempt and
                // its worker re-drive) must pass through, exactly like the
                // OwnedBySelf branch above; it stays non-releasable (the
                // reaper only acts on LifecycleVariant::Reserved).
                ReservationEvent::Consumed {
                    aggregate_id: holder,
                } if holder == aggregate_id => Ok(ClaimObstacle::OwnedBySelf(ReservationClaim {
                    key: stream_key(stream_id),
                    aggregate_id,
                    claim_version: last.stream_version,
                })),
                _ => Ok(ClaimObstacle::Permanent),
            },
            other => {
                // Unknown lifecycle event on a reservation stream: never
                // claim past an unknown — conservative.
                tracing::warn!(
                    stream_id,
                    event = other,
                    "unknown event on reservation stream; refusing claim (ADR-036 §2)",
                );
                Ok(ClaimObstacle::Permanent)
            }
        }
    }

    /// Reads the stream and returns its last event, paginating bounded rescans.
    /// Reservation streams hold at most a handful of events; the pagination
    /// loop exists so `has_more` cannot silently drop the tail of a
    /// pathological (never-expected) longer stream.
    async fn last_stream_event(
        &self,
        connection: &mut MultiplexedConnection,
        stream_id: &str,
    ) -> Result<Option<Event>, DomainError> {
        let mut from_version = 0u64;
        loop {
            let batch = connection
                .escan(stream_id, from_version, None, Some(100))
                .await
                .map_err(SierraError::from)
                .map_err(sierra_error)?;
            let last = batch.events.last().cloned();
            if !batch.has_more {
                return Ok(last);
            }
            // Continue after the highest version seen so far.
            from_version = last
                .as_ref()
                .map_or(from_version, |event| event.stream_version + 1);
        }
    }

    /// Low-level lifecycle append. Returns the `AppendInfo` on success and
    /// `None` exactly when the expected-version condition failed
    /// (`ErrorCode::WrongVer`) — every other `SierraError` is mapped by
    /// [`sierra_error`].
    async fn append_lifecycle(
        &self,
        connection: &mut MultiplexedConnection,
        stream_id: &str,
        event_name: &'static str,
        expected: ExpectedVersion,
        payload: &ReservationEvent,
    ) -> Result<Option<AppendInfo>, DomainError> {
        let mut buf = Vec::new();
        ciborium::into_writer(payload, &mut buf).map_err(|err| DomainError::Internal {
            reason: format!("unserializable reservation payload: {err}"),
        })?;

        let options = sierradb_client::EAppendOptions::new()
            .partition_key(stream_partition_key(stream_id))
            .expected_version(expected)
            .payload(buf);

        match connection.eappend(stream_id, event_name, options).await {
            Ok(info) => Ok(Some(info)),
            Err(err) => {
                let sierra = SierraError::from(err);
                match sierra.error_code() {
                    Some(ErrorCode::WrongVer) => Ok(None),
                    _ => Err(sierra_error(sierra)),
                }
            }
        }
    }
}

/// What stopped a claim attempt on an existing stream (classification of the
/// last event, ADR-036 §2).
enum ClaimObstacle {
    /// Our own earlier claim still tops the stream.
    OwnedBySelf(ReservationClaim),
    /// A released stream — the stream version to CAS re-claim at.
    Claimable(u64),
    /// A fresh-stream claim after an anomalous empty read.
    ClaimableAtFreshStream,
    /// Held by another aggregate, or consumed by a realized aggregate.
    Permanent,
}

/// SierraDB error mapping for the reservation store. The aggregate write path
/// maps raw event-store failures the same way
/// (`crates/infra/src/event_store/command_adapters.rs` → `map_executed_result`
/// catch-all), so this stays on one error surface.
fn sierra_error(err: SierraError) -> DomainError {
    DomainError::conflict(err.to_string())
}

/// CBOR payload decode helper: an unparsable lifecycle payload is permanent
/// data corruption, surfaced as `DomainError::Internal` with an error log
/// rather than entering any retry loop.
fn decode_lifecycle<T: DeserializeOwned>(
    payload: &[u8],
    stream_id: &str,
) -> Result<T, DomainError> {
    ciborium::from_reader(payload).map_err(|err| {
        tracing::error!(
            stream_id,
            "unparsable reservation payload ({err}) — treating as permanent (ADR-036 §2)",
        );
        DomainError::Internal {
            reason: format!("unparsable reservation payload: {err}"),
        }
    })
}

/// Strips the `reservation-` prefix: the opaque key of a full stream id.
fn stream_key(stream_id: &str) -> String {
    stream_id
        .strip_prefix(RESERVATION_STREAM_PREFIX)
        .unwrap_or(stream_id)
        .to_owned()
}
