# SPDX-License-Identifier: AGPL-3.0
# Copyright (C) 2024 Breakdown RS Contributors

name: Lint Workflows

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run actionlint
        uses: rhysd/actionlint@050851180362647816a73f22482b8402e0d65ae6 # v1.7.7
        with:
          filelist: .github/workflows/*.yml
